name: Deploy and Notify Frontend Build
on:
  push:
    branches: [main]

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: live.[website].com
          remote-user: youruser
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: /home/youruser/live.[website].com/wp-content/themes/anotherstep-custom-theme/
      
      - name: Trigger Build
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
          https://github.com \
          -d '{"event_type": "wordpres_update"}'